---
# Source: entando-k8s-operator-bundle/templates/entando-empty-tls-secret.yaml
apiVersion: v1
data:
  tls.crt: ''
  tls.key: ''
kind: Secret
metadata:
  name: entando-empty-tls-secret
type: kubernetes.io/tls
