name: PUB

on:
  push:
    tags:
      - 'v*'

env:
  PPL_TEMPLATE_VERSION: "v2.0.0"
  ENTANDO_BOT_TOKEN: ${{ secrets.ENTANDO_BOT_TOKEN }}
  PR_CHECKER_PATH: ".github/pr-title-checker-config.json"

  OPM_VERSION: "1.20.0"
  OPERATOR-SDK_VERSION: "1.20.0"
  DOCKER_BUNDLE_IMAGE_BASE_NAME: entandobuilduser/entando-k8s-operator-bundle
  DOCKER_INDEX_IMAGE_BASE_NAME: entandobuilduser/entando-k8s-index
  DOCKER_IMAGE_ARCHITECTURE: linux/amd64,linux/arm64
  DOCKER_IMAGE_CONTEXT: .
  DOCKER_BUNDLE_IMAGE_FILE: Dockerfile.community
  DOCKER_INDEX_IMAGE_FILE: index.Dockerfile
  DOCKER_IMAGE_PUSH: true

jobs:

  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ${{ env.PR_CHECKER_PATH }}

  publication:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          opm: ${{ env.OPM_VERSION }}
          operator-sdk: ${{ env.OPERATOR-SDK_VERSION }}

      - name: Build steps
        run: |
          ./generate-manifests.sh --version "${ENTANDO_PRJ_VERSION}" --mainline "$ENTANDO_OPT_MAINLINE_VERSION"

      - name: Docker meta bundle
        id: meta-bundle
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_BUNDLE_IMAGE_BASE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr,value={{base_ref}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{base_ref}}

      - name: Docker meta index
        id: meta-index
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_INDEX_IMAGE_BASE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr,value={{base_ref}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{base_ref}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.DOCKER_IMAGE_ARCHITECTURE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
          password: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}

      - name: Build and push operator bundle image
        id: build-and-push-bundle
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKER_IMAGE_CONTEXT }}
          file: ${{ env.DOCKER_BUNDLE_IMAGE_FILE }}
          push: ${{ env.DOCKER_IMAGE_PUSH }}
          tags: ${{ steps.meta-bundle.outputs.tags }}
          labels: ${{ steps.meta-bundle.outputs.labels }}
          platforms: ${{ env.DOCKER_IMAGE_ARCHITECTURE }}

      - name: Bundle validation
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          for tag in $TAGS; do
            operator-sdk bundle validate "$tag"
          done

      - name: Build Dockerfile for operator index image
        env:
          DIGEST: ${{ steps.build-and-push-bundle.outputs.digest }}
        run: |
          export MY_VERSION=$(yq eval '.spec.version' manifests/k8s-116-and-later/community-deployment/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml)
          echo "> Found version $MY_VERSION"
          NEW_BUNDLE_BASE_IMAGE="${BUNDLES}registry.hub.docker.com/$DOCKER_BUNDLE_IMAGE_BASE_NAME"
          NEW_BUNDLE_BASE_IMAGE="${NEW_BUNDLE_BASE_IMAGE}@${DIGEST}"
          BUNDLES="${BUNDLES}${NEW_BUNDLE_BASE_IMAGE}"
          opm index add --bundles "${BUNDLES}" --container-tool docker --binary-image quay.io/operator-framework/opm:latest --generate

      - name: Build and push operator index image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKER_IMAGE_CONTEXT }}
          file: ${{ env.DOCKER_INDEX_IMAGE_FILE }}
          push: ${{ env.DOCKER_IMAGE_PUSH }}
          tags: ${{ steps.meta-index.outputs.tags }}
          labels: ${{ steps.meta-index.outputs.labels }}
          platforms: ${{ env.DOCKER_IMAGE_ARCHITECTURE }}